# .github/labels.yml
- name: core
  color: "B60205"   # red
  description: Engine / core logic

- name: cli
  color: "0E8A16"   # green
  description: Command-line interface

- name: python interface
  color: "1D76DB"   # blue
  description: Public Python API
